version: '3'
services:
  grpc_server:
      build: server
      ports:
        - 8080:8080
  express:
      build: express
      ports:
        - 8081:8081
      depends_on:
        - grpc_server
      links:
        - grpc_server
  nginx:
      image: nginx:latest
      ports:
          - "8082:80"
      volumes:
          - ./php:/php
          - ./site.conf:/etc/nginx/conf.d/default.conf
      links:
        - php
        - grpc_server
      depends_on:
        - grpc_server

  php:
      build: ./php
      volumes:
        - ./php:/php
      depends_on:
        - grpc_server
